 const list = [
    {
      id: 1,
      name: "SVM",
      contact: "6397214461",
      address: "Kamla nagar ",
      city: "Agra",
      state: "Uttar Pradesh",
      image: "image/1.jpg",
      email: "akashsharma0801@gmail.com",
    },
    {
      id: 2,
      name: "Akash Sharma",
      contact: "6397214461",
      address: "Dayal Bagh, Agra",
      city: "Agra",
      state: "Uttar Pradesh",
      image: "image/2.jpg",
      email: "akashsharma0801@gmail.com",
    },
    {
      id: 3,
      name: "Akash Sharma",
      contact: "6397214461",
      address: "Dayal Bagh, Agra",
      city: "Agra",
      state: "Uttar Pradesh",
      image: "image/3.jpg",
      email: "akashsharma0801@gmail.com",
    },
    {
      id: 4,
      name: "SVM",
      contact: "6397214461",
      address: "Dayal Bagh, Agra",
      city: "Agra",
      state: "Uttar Pradesh",
      image: "image/4.jpg",
      email: "akashsharma0801@gmail.com",
    },
    {
      id: 5,
      name: "Akash Sharma",
      contact: "6397214461",
      address: "Dayal Bagh, Agra",
      city: "Agra",
      state: "Uttar Pradesh",
      image: "image/5.jpg",
      email: "akashsharma0801@gmail.com",
    },
    {
      id: 6,
      name: "SVM",
      contact: "6397214461",
      address: "Dayal Bagh, Agra",
      city: "Agra",
      state: "Uttar Pradesh",
      image: "image/7.jpg",
      email: "akashsharma0801@gmail.com",
    },
    {
      id: 7,
      name: "Akash Sharma",
      contact: "6397214461",
      address: "Dayal Bagh, Agra",
      city: "Agra",
      state: "Uttar Pradesh",
      image: "image/1.jpg",
      email: "akashsharma0801@gmail.com",
    },
    {
      id: 8,
      name: "Akash Sharma",
      contact: "6397214461",
      address: "Dayal Bagh, Agra",
      city: "Agra",
      state: "Uttar Pradesh",
      image: "image/9.jpg",
      email: "akashsharma0801@gmail.com",
    },
  ];

  export default list;